from Modules.about_tab import AboutTab
from Modules.download_manager import Downloader
from Modules.parameter_tab import ParameterTab
from Modules.text_manager import TextTab
from .about_tab import AboutTab
from .dialog import Dialog
from .download_element import Download
from .download_tab import MainTab
from .main_window import MainWindow
from .parameterTree import ParameterTree
